name: 📊 Static Checks
on: [push, pull_request]

jobs:
  format:
    name: File formatting (file_format.sh)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install APT dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: dos2unix moreutils

      - name: File formatting checks (file_format.sh)
        run: |
          bash ./.github/scripts/file_format.sh
